src/Entity/Attack.php
<?php

namespace App\Entity;

use App\Repository\AttackRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AttackRepository::class)]
class Attack
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Label;

    #[ORM\Column(type: 'text')]
    private $Description;

    #[ORM\ManyToMany(targetEntity: Pokemon::class, mappedBy: 'attacks')]
    private $pokemon;

    #[ORM\ManyToOne(targetEntity: Type::class, inversedBy: 'Attacks')]
    private $type;

    #[ORM\Column(type: 'string', length: 255)]
    private $Category;

    #[ORM\Column(type: 'string', length: 255)]
    private $Power;

    #[ORM\Column(type: 'string', length: 255)]
    private $Accuracy;

    #[ORM\Column(type: 'string', length: 255)]
    private $PP;

    #[ORM\Column(type: 'string', length: 255)]
    private $MakesContact;

    public function __construct()
    {
        $this->pokemon = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): self
    {
        $this->Label = $Label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Pokemon>
     */
    public function getPokemon(): Collection
    {
        return $this->pokemon;
    }

    public function addPokemon(Pokemon $pokemon): self
    {
        if (!$this->pokemon->contains($pokemon)) {
            $this->pokemon[] = $pokemon;
            $pokemon->addAttack($this);
        }

        return $this;
    }

    public function removePokemon(Pokemon $pokemon): self
    {
        if ($this->pokemon->removeElement($pokemon)) {
            $pokemon->removeAttack($this);
        }

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getPower(): ?string
    {
        return $this->Power;
    }

    public function setPower(string $Power): self
    {
        $this->Power = $Power;

        return $this;
    }

    public function getAccuracy(): ?string
    {
        return $this->Accuracy;
    }

    public function setAccuracy(string $Accuracy): self
    {
        $this->Accuracy = $Accuracy;

        return $this;
    }

    public function getPP(): ?string
    {
        return $this->PP;
    }

    public function setPP(string $PP): self
    {
        $this->PP = $PP;

        return $this;
    }

    public function getMakesContact(): ?string
    {
        return $this->MakesContact;
    }

    public function setMakesContact(string $MakesContact): self
    {
        $this->MakesContact = $MakesContact;

        return $this;
    }
}

src/Controller/AttacksController.php
<?php

namespace App\Controller;

use App\Form\FilterAttacksType;
use App\Repository\AttackRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AttacksController extends AbstractController
{

    private PaginatorInterface $paginator;
    private AttackRepository $attackRepository;

    public function __construct(
        AttackRepository $attackRepository,
        PaginatorInterface $paginator
    ) {
        $this->attackRepository = $attackRepository;
        $this->paginator = $paginator;
    }
    #[Route('/attacks', name: 'app_attacks')]
    public function index(Request $request): Response
    {
        $qb = $this->attackRepository->getQbAll();

        $formFilter = $this->createForm(FilterAttacksType::class);
        $formFilter->handleRequest($request);

        if ($formFilter->isSubmitted() && $formFilter->isValid()) {
            $qb = $this->attackRepository->updateQbByData($qb, $formFilter->getData());  
        }

        $pagination = $this->paginator->paginate(
            $qb, //La query
            $request->query->getInt('page',1), //Le numero de page de depart
            25 //Le nombre de résultat pas page
        );

        return $this->render('attacks/index.html.twig', [
            'pagination' => $pagination,
            'form' => $formFilter->createView(),
        ]);
    }

    #[Route('/attack/{id}', name: 'show_attack')]
    public function getOneAttackById(int $id): Response
    {
        $attackEntity = $this->attackRepository->find($id);
        return $this->render('attacks/show.html.twig', [
            'myAttack' => $attackEntity,
        ]);
    }

}

templates/attacks/index.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Hello AttacksController!{% endblock %}

{% block body %}
<div class="container text-center">
<h1>All Attacks</h1>

    {{ form_start(form) }}
    <div class="row">
        <div class="col-6">
            {{form_row(form.power)}}
        </div>
        <div class="col-6">
            {{form_row(form.accuracy)}}
        </div>
        <div class="col-6">
            {{form_row(form.category)}}
        </div>
        <div class="col-6">
            {{form_row(form.makesContact)}}
        </div>
    </div>
    {{ form_end(form) }}

    <div class="col-12">
        <table class="table table-striped">
            <tr class="row">
                <td class="col-2"><b>Name</b></td>
                <td class="col-2"><b>Type</b></td>
                <td class="col-2"><b>Category</b></td>
                <td class="col-1"><b>Power</b></td>
                <td class="col-2"><b>Accuracy</b></td>
                <td class="col-1"><b>PP</b></td>
                <td class="col-2"><b>Makes contact?</b></td>
            </tr>

            {% for attack in pagination %}
            <tr class="row">
                <td class="col-2">
                    <p>{{ attack.label }}</p>
                </td>
                <td class="col-2">
                    <p class="{{ attack.type.label }} type">{{ attack.type.label }}</p>
                </td>
                <td class="col-2">
                    <p>{{ attack.category }}</p>
                </td>
                <td class="col-1">
                    <p>{{ attack.power }}</p>
                </td>
                <td class="col-2">
                    <p>{{ attack.accuracy }}</p>
                </td>
                <td class="col-1">
                    <p>{{ attack.PP }}</p>
                </td>
                <td class="col-2">
                    <p>{{ attack.MakesContact }}</p>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="mb-3">
    {{ knp_pagination_render(pagination) }}
</div>

</div>

{% endblock %}

templates/attacks/show.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Hello AttacksController!{% endblock %}

{% block body %}


{% endblock %}